### ISSUE TITLE
Implement Sound Notifications when User is on another tab

### ISSUE THREAD

**Issue by Ankit-Roy-CSE** [lugnitdgp/Chatopia_GSOC_Heat_24#20]
Implement Notifications with Sound whenever a message is received and user is on another tab .

**Comment by Arnob-B** [comment]
Hey worked on a similar kind of notification system , So you may assign this to me

**Comment by Arnob-B** [comment]
hey i hv created a PR for this issue
plse check chat out [link](https://github.com/lugnitdgp/Chatopia_GSOC_Heat_24/pull/26)
