### ISSUE TITLE
Enhance Sign-In Feedback with Clear Error Messages

### ISSUE THREAD

**Issue by kartik-212004** [lugnitdgp/Chatopia_GSOC_Heat_24#25]
The sign-in page shows a pop-up message "invalid credentials" for incorrect email or password, lacking specific details on the issue.

**Current Behavior:**  
- Users see a generic "invalid credentials" message regardless of whether the email format is wrong or the password is too short.

**Expected Behavior:**  
- Display specific error messages, such as:
  - "Invalid email format."
  - "Password must be at least X characters long."
  
**Proposed Solution:**  
- Use **Zod** for validation to enhance error messaging.

**Steps to Reproduce:**  
1. Go to the sign-in page.
2. Enter incorrect credentials.
3. Observe the pop-up message.

**Comment by Ankit-Roy-CSE** [comment]
@kartik-212004 Assigned , thanks for contributing !
