### ISSUE TITLE
Integrate socket.io into friend requests

### ISSUE THREAD

**Issue by Ankit-Roy-CSE** [lugnitdgp/Chatopia_GSOC_Heat_24#5]
Make the sending & receiving of friend requests real-time using web sockets with socket.io

**Comment by asmb123** [comment]
Can i work on this?

**Comment by Ankit-Roy-CSE** [comment]
> Can i work on this?

Hey asmb123 , we are sorry to let you know that the issue has been resolved and been closed already . However it would be really helpful if you could work on making the friend requests page responsive , for which a new issue has been raised ?
